### PR TITLE
Remove preset files from %post directive

### PR DESCRIPTION
**Pull request by strider**
This patch removes the following preset files from %post:
- 80-insights-register.preset
- 80-rhcd-register.preset

Signed-off-by: Gael Chamoulaud (Strider) <gchamoul@redhat.com>

### CODE REVIEW

**Review by subpop — APPROVED** [review]
LGTM

**Comment by ahitacat** [comment]
LGTM :seal:

**Review by ahitacat — APPROVED** [review]
LGTM :seal:

**Comment by strider** [comment]
Approved by 2 people and tested successfully by Alba on rhel8/9 this morning.

Merging it now.

**Pull request merged**
